### ISSUE TITLE
task: Clean up old Pull Requests

### ISSUE THREAD

**Issue by chrisman** [Skookum/bamboozled#47]
There are a lot of old pull requests that need cleaning up!

There are several that are probably candidate for closing without merging:

- "Old" ones, however we want to make that arbitrary cut. Say, 2016 and older.

- Incomplete PRs, ones marked WIP

- PRs not currently passing tests

**Comment by chrisman** [comment]
## PR Checklist

- [x] #2 -- Login API and option to not JSON parse tabulated data -- 4-5 years old. Not passing CI. Candidate for closing. **update**: closed

- [ ] #10  -- WIP:Get table tabular data -- ~4yrs old. "WIP" Not passing CI. Candidate for closing.

- [ ] #14 -- Fix fetching API endpoints that return array -- ~3yrs old. Not passing CI. Candidate for closing.

- [ ] #31 -- Remove hound in favor of pronto -- ~3yrs old. Not passing CI. Candidate for closing.

- [ ] #35 -- Fix fetching preferredName when getting all fields -- ~2yrs old. Not passing CI. Candidate for deletion.

- [ ] #41 -- Add info for release 0.2.0 -- 1yr old. Not passing CI. It's from Glenn. Unsure

- [ ] #42 -- Implement fetching employees via the custom report endpoint -- pretty recent. not passing CI. (2nd open PR currently open by @artfuldodger)

- [ ] #43 -- Allow API domain to be specified -- Pretty recent. Passing CI. candidate for review!

**Comment by chrisman** [comment]
## template for closing a PR

```
Hi, @contributer 👋

We're currently in the process of cleaning up this repo and preparing to release the next version of this gem.

This pull request is really old at this point, and it's not currently passing our CI check. So I'm going to go ahead and close it. That said, we really value and appreciate your contribution, and if you want to update your PR and resubmit it, we will 100% welcome it and will reconsider it at that time!

Thanks!
```

**Comment by artfuldodger** [comment]
It seems like a lot of the "not passing CI" issues are because rubocop's mad at a line being touched that breaks a rule regardless of whether the rule was already being broken or not, for the record. :)

**Comment by chrisman** [comment]
Closing this out. It's goal was to get us to v0.2.0, and we got there!
